# CodeRabbit Configuration File
# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
# https://coderabbit.ai/docs/get-started/customize-coderabbit

early_access: true
reviews:
  request_changes_workflow: true
  auto_review:
    enabled: true
  poem: false
chat:
  auto_reply: true
