name: Add or update folder
description: Service interface for adding or updating Google folders.
title: Add or update folder
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to request a folder in the Google Cloud Platform resource hierarchy.

  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: google-folder-path
    attributes:
      label: "Google folder path:"
      description: The path of the Google folder to create or update.
      placeholder: Platform - Google Cloud Kubernetes Engine/Autopilot
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: "Additional comments:"
      description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false
