name: Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/gcp-plan-and-apply.yml@main
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production Infrastructure: Global"
      service_account: plt-lz-hierarchy-github@ptl-lz-terraform-tf62-prod.iam.gserviceaccount.com
      terraform_state_bucket: plt-lz-hierarchy-e194-prod
      terraform_version: 1.3.9
      terraform_workspace: global-production
      working_directory: global/infra
      workload_identity_provider: projects/134040294660/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="organization_id=${{ secrets.ORGANIZATION_ID }}" -var="customer_id=${{ secrets.CUSTOMER_ID }}"
