name: Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: "Main"
    uses: osinfra-io/github-opentofu-gcp-called-workflows/.github/workflows/plan-and-apply.yml@e3c59e43f2458550c7f13b6369fb6978b6f42c6e # v0.2.9
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production: Main"

      # This service account needs to be added to the Groups Admin system role in the the Google Workspace Admin Console

      service_account: plt-lz-hierarchy-github@plt-lz-backend-tf5f-prod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/plt-lz-backend-tf5f-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=tfvars/production.tfvars
      opentofu_state_bucket: plt-lz-hierarchy-d3c2-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-production
      workload_identity_provider: projects/134040294660/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
